name: 🐞 Bug report
description: Report a problem or regression
labels: [bug]
assignees: "Neodevils"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this issue.
  - type: input
    id: summary
    attributes:
      label: Summary
      description: Short, clear description of the bug
      placeholder: Example: CommandHandler fails to register commands
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: What sequence causes the bug?
      placeholder: 1. Run command …\n2. Observe behavior …
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Paste any errors or stack traces (use code blocks)
      render: shell
